name: madproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/petpal.jpg
   - assets/emergency.jpg
   - assets/adoption.jpg
   - assets/market.jpg
   - assets/events.jpg
   - assets/PUPPY.jpg
   - assets/PERSIAN.jpg
   - assets/LABRADOR.jpg
   - assets/HAMSTER.jpg
   - assets/python.jpg
   - assets/petservices.jpg
   - assets/logo.jpg
   - assets/adoption1.jpg
   - assets/adoption2.jpg
   - assets/shop1.jpg
   - assets/shop2.jpg
   - assets/shope3.jpg